workflows:
  build_opnmanager_android:
    name: Build OPNManager Android v3.1.2 (Debug)
    max_build_duration: 90
    environment:
      vars:
        ANDROID_SDK_ROOT: /opt/android-sdk
        npm_config_optional: false
    scripts:
      # 1️⃣ Pulizia ambiente
      - echo "Cleaning node_modules..."
      - rm -rf node_modules package-lock.json

      # 2️⃣ Installa dipendenze Node
      - echo "Installing Node dependencies..."
      - npm install

      # 3️⃣ Compila frontend (Vite/Svelte)
      - echo "Building frontend..."
      - npm run build

      # 4️⃣ Installa Rust, Tauri CLI e build APK in un'unica shell
      - bash -c "
          echo 'Installing Rust...';
          curl https://sh.rustup.rs -sSf | sh -s -- -y;
          export PATH=\"$HOME/.cargo/bin:$PATH\";
          cargo --version;
          echo 'Installing Tauri CLI...';
          cargo install tauri-cli --locked || true;
          echo 'Creating debug keystore...';
          mkdir -p android/debug;
          keytool -genkeypair -v -keystore android/debug/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname \"CN=Debug, OU=Dev, O=Dev, L=City, S=State, C=US\";
          echo 'Building Android debug APK...';
          cargo tauri android build --debug --signing-key android/debug/debug.keystore --alias androiddebugkey --storepass android --keypass android
        "

    artifacts:
      - "**/app-debug.apk"

    publishing:
      email:
        recipients:
          - your@email.com
        notify:
          success: true
          failure: true
