workflows:
  build_opnmanager_android:
    name: Build OPNManager Android v3.1.2
    max_build_duration: 60
    environment:
      vars:
        ANDROID_SDK_ROOT: /opt/android-sdk
    scripts:
      # 1️⃣ Installa le dipendenze Node
      - echo "Installing Node dependencies..."
      - npm install

      # 2️⃣ Compila la parte frontend
      - echo "Building frontend..."
      - npm run build

      # 3️⃣ Installa la CLI Tauri
      - echo "Installing Tauri CLI..."
      - cargo install tauri-cli --locked || true

      # 4️⃣ Build Android APK
      - echo "Building Android APK..."
      - cargo tauri android build --release

    artifacts:
      - "**/app-release.apk"
      - "**/app-universal-release.aab"

    publishing:
      email:
        recipients:
          - your@email.com
        notify:
          success: true
          failure: true
