workflows:
  build_opnmanager_android:
    name: Build OPNManager Android v3.1.2 (Debug)
    max_build_duration: 120
    environment:
      vars:
        npm_config_optional: false
    scripts:
      - |
        echo "Cleaning node_modules..."
        rm -rf node_modules package-lock.json

      - |
        echo "Installing Node dependencies..."
        npm install

      - |
        echo "Building frontend..."
        npm run build

      - |
        echo "Installing Rust and Tauri CLI (globally)..."
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        source $HOME/.cargo/env
        export PATH="$HOME/.cargo/bin:$PATH"
        cargo --version
        cargo install tauri-cli --locked || true

      - |
        echo "Installing Android SDK/NDK/build-tools..."
        mkdir -p $HOME/android-sdk/cmdline-tools
        curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip sdk-tools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$ANDROID_SDK_ROOT/platform-tools:$PATH

      - |
        echo "Initializing Tauri Android project in src-tauri..."
        source $HOME/.cargo/env
        export PATH="$HOME/.cargo/bin:$PATH"
        cd $CM_BUILD_DIR/src-tauri
        ls -l Cargo.toml
        if [ ! -f "Cargo.toml" ]; then
          echo "❌ Cargo.toml not found in src-tauri. Stopping build."
          exit 1
        fi
        if [ ! -d "gen/android" ]; then
          npx tauri android init
        fi

      - |
        echo "Creating debug keystore..."
        cd $CM_BUILD_DIR
        mkdir -p android/debug
        keytool -genkeypair -v -keystore android/debug/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Debug, OU=Dev, O=Dev, L=City, S=State, C=US"

      - |
        echo "Building Android debug APK..."
        source $HOME/.cargo/env
        export PATH="$HOME/.cargo/bin:$PATH"
        cd $CM_BUILD_DIR
        cargo tauri android build --debug -- \
          --signing-key android/debug/debug.keystore \
          --alias androiddebugkey \
          --storepass android \
          --keypass android

    artifacts:
      - "**/app-debug.apk"

    publishing:
      email:
        recipients:
          - your@email.com
        notify:
          success: true
          failure: true
