workflows:
  build_opnmanager_android:
    name: Build OPNManager Android v3.1.2 (Debug)
    max_build_duration: 60
    environment:
      vars:
        ANDROID_SDK_ROOT: /opt/android-sdk
    scripts:
      # 1️⃣ Installa dipendenze Node
      - echo "Installing Node dependencies..."
      - npm install

      # 2️⃣ Compila frontend (SvelteKit)
      - echo "Building frontend..."
      - npm run build

      # 3️⃣ Installa Tauri CLI
      - echo "Installing Tauri CLI..."
      - cargo install tauri-cli --locked || true

      # 4️⃣ Crea il keystore di debug
      - echo "Creating debug keystore..."
      - mkdir -p android/debug
      - keytool -genkeypair -v -keystore android/debug/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Debug, OU=Dev, O=Dev, L=City, S=State, C=US"

      # 5️⃣ Build Android APK (debug firmato)
      - echo "Building Android debug APK..."
      - cargo tauri android build --debug --signing-key android/debug/debug.keystore --alias androiddebugkey --storepass android --keypass android

    artifacts:
      - "**/app-debug.apk"

    publishing:
      email:
        recipients:
          - gabriele.petrecca@gmail.com
        notify:
          success: true
          failure: true
