name: Init Android Tauri

on:
  workflow_dispatch:

jobs:
  init-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Tauri CLI (NPM)
        run: |
          cd src-tauri
          npm install @tauri-apps/cli

      - name: Init Tauri Android
        run: |
          cd src-tauri
          npx tauri android init
          ls -l gen

      - name: Upload generated android folder
        uses: actions/upload-artifact@v4
        with:
          name: tauri-android-project
          path: src-tauri/gen/android
